server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    name: ppr_db
    url: jdbc:postgresql://localhost:5432/ppr_db
    username: postgres
    password: password
    platform: postgresql
    continue-on-error: true
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE

---

spring:
  profiles: staging
  datasource:
    url: ${DATABASE_URL}
    platform: postgresql
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE

---

spring:
  profiles: production
  datasource:
    url: ${DATABASE_URL}
    platform: postgresql
    continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE

